on: pull_request

name: Workflow templates

jobs:
  check-yaml:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - run: |
          docker pull mikefarah/yq
          for f in $(find github/workflows/ -name '*.yaml'); do
            docker run --rm --volume "$PWD":/workdir mikefarah/yq "$f" > /dev/null
          done

  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: arduino/setup-task@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - run: |
          task lint:shell-script
